### ISSUE TITLE
Add back assembly as option

### ISSUE THREAD

**Issue by roanutil** [heroesofcode/swift-explorer#3]
Adding the ability to view LLVM IR is a great choice but it seems unfortunate to throw out assembly. Could the option to choose between the two be added? Or show both side by side?

**Comment by joaolfp** [comment]
I'm already working on putting LLVM and Assembly side by side, I'll include them in the next version

**Comment by joaolfp** [comment]
Update to version 1.2.0. I'll leave the dmg link below.

[Download dmg](https://github.com/heroesofcode/swift-explorer/releases/download/1.2.0/SwiftExplorer.dmg)
