### ISSUE TITLE
Add option to set compiler optimization level

### ISSUE THREAD

**Issue by roanutil** [heroesofcode/swift-explorer#9]
It seems that `swiftc` defaults to `-Onone` (no optimizations). It would be helpful if the optimization level could be controlled instead of accepting the default.

## swiftc optimization flags
- `-Onone`: Compile without any optimization
- `-Osize`: Compile with optimizations and target small code size
- `-Ounchecked`: Compile with optimizations and remove runtime safety checks
- `-O`: Compile with optimizations

**Comment by roanutil** [comment]
If you're open to this change, I can make a PR for it soon

**Comment by joaolfp** [comment]
Hi @roanutil, I liked the idea ... feel free to open a PR so we can have these changes

**Comment by joaolfp** [comment]
Thanks for the contribution @roanutil, I just generated a version 1.4.0. I'll leave the dmg file below

[Download dmg - version 1.4.0](https://github.com/heroesofcode/swift-explorer/releases/download/1.4.0/SwiftExplorer.dmg)
